INSERT INTO `residuo` (`id_residuo`, `nombre_residuo`) VALUES
  (18, 'Aceite Vegetal'),
  (5, 'Aluminio'),
  (13, 'Anteojos - Estuches'),
  (19, 'Bolsa de Alimento'),
  (9, 'Botella de Amor'),
  (23, 'Botella de Vidrio'),
  (4, 'Botella Plastica'),
  (7, 'Botella salsa Tomate'),
  (11, 'Botellas Aplastadas'),
  (3, 'Cartón'),
  (24, 'Corcho'),
  (20, 'Electrodomestico'),
  (14, 'Foco LED'),
  (6, 'Frasco de Vidrio'),
  (10, 'Lata Hojalata'),
  (16, 'Llave de bronce'),
  (12, 'Maple de Huevo'),
  (2, 'Papel'),
  (21, 'Pila'),
  (15, 'Radiografía'),
  (8, 'Tapitas Plasticas'),
  (17, 'Tela'),
  (22, 'Telgopor'),
  (1, 'TetraPack');