INSERT INTO `ecopunto` (`id_ecopunto`, `nombre`, `ubicacion`, `horario`, `dia`) VALUES
  (1, 'Chacra 32-33 Feria Franca', NULL, NULL, NULL),
  (2, 'Cruz Roja', NULL, NULL, NULL),
  (3, 'B° Alta Gracia', NULL, NULL, NULL),
  (4, 'Club de los Abuelos', NULL, NULL, NULL),
  (5, 'Cancha Guarani', NULL, NULL, NULL),
  (6, 'Mercado Concentrador ', NULL, NULL, NULL),
  (7, 'Murga de La Estacion', NULL, NULL, NULL),
  (8, 'AgroRiegos-Optimus', NULL, NULL, NULL),
  (9, 'Villa Cabello', NULL, NULL, NULL),
  (10, 'Manantiales, Hijos del Rey', NULL, NULL, NULL),
  (11, 'Chacra 83 Kiosco de Ada', NULL, NULL, NULL),
  (12, 'Chacra 193 B° Laurel', NULL, NULL, NULL),
  (13, 'Chacra 92 Centro Jubilados', NULL, NULL, NULL),
  (14, 'Chacra 189 Comisión Vecinal', NULL, NULL, NULL),
  (15, 'B° A-4', NULL, NULL, NULL),
  (16, 'Centro de Educación Ambiental', NULL, NULL, NULL),
  (17, 'B° San Jorge', NULL, NULL, NULL),
  (18, 'B° San Pedro', NULL, NULL, NULL),
  (19, 'B° Mini City', NULL, NULL, NULL),
  (20, 'B° Sur Argentino ', NULL, NULL, NULL),
  (21, 'B° El Porvenir I', NULL, NULL, NULL);